on: [push]
name: Linux_Container_Workflow

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - name: 'Checkout GitHub Action'
          uses: actions/checkout@main
        
        # Build the SERVER container 
        - name: 'Build and push SERVER image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./server/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/server:latest

      # Create the ENV for the FRONTEND
        - name: Create env file
          uses: SpicyPizza/create-envfile@v1
          with: 
            envkey_REACT_APP_ENVIRONMENT: ${{ secrets.REACT_APP_ENVIRONMENT }}
            envkey_REACT_APP_API_PROD: ${{ secrets.REACT_APP_API_PROD }}
            envkey_REACT_APP_STORAGESASTOKEN: ${{ secrets.REACT_APP_STORAGESASTOKEN }}
            envkey_REACT_APP_SECRET_TOKEN : ${{ secrets.REACT_APP_SECRET_TOKEN }}
            envkey_directory: ./.
            file_name: .env

      # Build the FRONTEND  container 
        - name: 'Build and push FRONTEND image'
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            username: ${{ secrets.REGISTRY_USERNAME }}
            password: ${{ secrets.REGISTRY_PASSWORD }}
        - run: |
            docker build ./memeteca/. -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest

